export const Dokumenttype = {
  LEGEERKLÆRING: 'LEGEERKLÆRING_SYKEHUS',
  ANDRE_MEDISINSKE_OPPLYSNINGER: 'MEDISINSKE_OPPLYSNINGER',
  MANGLER_MEDISINSKE_OPPLYSNINGER: 'ANNET',
  UKLASSIFISERT: 'UKLASSIFISERT',
};